spring.application.name=laplana

spring.datasource.url=${certificate_url}
spring.datasource.username=${certificate_supabase_username}
spring.datasource.password=${certificate_database_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

supabase.url=${certificate_supabase_storage_url}
supabase.service.role.key=${certificate_supabase_service_role_key}